### ISSUE TITLE
Updating the properties too quickly

### ISSUE THREAD

**Issue by mkohanim** [UniversalDevicesInc-PG3/udi-wirelesstag-poly#34]
It seems that short poll has no impact on the interval for updating the nodes/controls.

**Comment by jimboca** [comment]
That is correct.  That's the nice part about wireless tags :) There is no polling, the updates are pushed from the hub as it sees the changes.
Are you asking if the node server should queue up those changes and only send on short poll's?

**Comment by jimboca** [comment]
@mkohanim was there something you wanted changed here?

**Comment by mkohanim** [comment]
No?

With kind regards,

******************************
Michel Kohanim

(p) 818.631.0333
http://www.universal-devices.com
******************************
________________________________
