### ISSUE TITLE
Event State status gone and no longer detected in a program  

### ISSUE THREAD

**Issue by SteveHoyt** [UniversalDevicesInc-PG3/udi-wirelesstag-poly#50]
I have had a program running for weeks now, that when it detects motion turns on a garage light plugged in to a kasa hs110. It suddenly stopped working a few days ago.   I am not sure if it is related to updates made to the tag manager or not. I also had a power outage here that messed up my network, so that may have caused the problem. In any case, i deleted the kasa and tag node servers and reinstalled them.  All seemed to go well. I also verified that they were gone from the admin console and readded  them after I reinstalled the 2 node servers. I still do not see any info in the event state. Other tags also have no value for event state. Any idea where to go from here?  See info below. Thanks Steve
<img width="634" alt="Screen Shot 2022-02-23 at 9 48 37 AM" src="https://user-images.githubusercontent.com/97555417/155418957-a91fd621-87ab-4cb3-9193-34786ab49adf.png">
<img width="608" alt="Screen Shot 2022-02-23 at 9 44 43 AM" src="https://user-images.githubusercontent.com/97555417/155418995-4dd31c82-9460-4368-ab56-5a1ffa40d641.png">
<img width="1094" alt="Screen Shot 2022-02-23 at 9 44 15 AM" src="https://user-images.githubusercontent.com/97555417/155419012-27eea897-2010-496b-9387-b3a3d17433c5.png">
[WirelessTag_2-23-2022_94646_AM.zip](https://github.com/UniversalDevicesInc-PG3/udi-wirelesstag-poly/files/8128188/WirelessTag_2-23-2022_94646_AM.zip)

**Comment by jimboca** [comment]
I reviewed the log and the Tag Manager is is not sending back any any motion detected events, 
But I don't like that Event Stage is empty, so let me look at that more.

**Comment by jimboca** [comment]
Found it... an accidental typo.  Released 3.1.2
