### ISSUE TITLE
hundreds of alerts being generated by url request to tag hub

### ISSUE THREAD

**Issue by SteveHoyt** [UniversalDevicesInc-PG3/udi-wirelesstag-poly#53]
My polisy has suddenly started to have a bunch of problems. The rain machine node server now gets an error saying "controller not found in database"....not your problem. In an attempt to fix it I tried reinstalling the rain machine app. That did not fix anything. But I also tried rebooting the polisy and PG3. After trying all this now the tag node server is issuing hundreds of bad url requests  I am posting this for your info only. I suspect I will need to create a ticket in the morning to fix my polisy, but wanted you to know in case there is anything in your program you might want to check. See below for info
<img width="1164" alt="Screen Shot 2022-03-13 at 4 36 48 PM" src="https://user-images.githubusercontent.com/97555417/158084547-789b27fd-1920-48f6-9924-5022c1208d8a.png">

[WirelessTag_3-13-2022_43331_PM.zip](https://github.com/UniversalDevicesInc-PG3/udi-wirelesstag-poly/files/8240838/WirelessTag_3-13-2022_43331_PM.zip)
<img width="1164" alt="Screen Shot 2022-03-13 at 4 34 48 PM" src="https://user-images.githubusercontent.com/97555417/158084656-9af8356c-ff5f-454d-9e6b-9af25bc4a9f2.png">

.

**Comment by jimboca** [comment]
This issue was reported to support a while back and they think it is now fixed. There are a couple posts about it on the forum. Support said:

I found the issue. The signal and transmit power were not supplied if the "buffer multiple data point" option is enabled. It is all fixed now, please try again.

**Comment by SteveHoyt** [comment]
you can close
