### ISSUE TITLE
Rest server false unable to start NSDATA

### ISSUE THREAD

**Issue by SteveHoyt** [UniversalDevicesInc-PG3/udi-wirelesstag-poly#54]
Hi

I was forced to migrate to IoP this weekend, due to certain data types no longer being supported in the 994 version of ISY. It mostly went well. However I had to delete all my node servers and reinstall them. I got the above error when trying to install wstag. Any suggestions how to get rid of it.

Thanks

Logs and screen shots attached
<img width="1491" alt="Screen Shot 2022-03-20 at 9 07 02 AM" src="https://user-images.githubusercontent.com/97555417/159172286-cc14fd87-5dbc-4201-8e4c-cd584453b50f.png">
<img width="1176" alt="Screen Shot 2022-03-20 at 9 21 26 AM" src="https://user-images.githubusercontent.com/97555417/159172291-91b78738-dcad-4e0f-b556-eeaa4a205d3c.png">
[WirelessTag_3-20-2022_90637_AM.zip](https://github.com/UniversalDevicesInc-PG3/udi-wirelesstag-poly/files/8311647/WirelessTag_3-20-2022_90637_AM.zip)
.

**Comment by jimboca** [comment]
This is an issue with 3.0.47 and @bpaauwe is aware.

**Comment by SteveHoyt** [comment]
Ok no problem…Is there a forum I should watch for the fix or will you post on wstags when fixed.

Steve

**Comment by jimboca** [comment]
The main PG3 forum where Bob posts his release notes

**Comment by jimboca** [comment]
PG3 3.0.48 is released which should fix this issue.
